### PR TITLE
83: Add complete Gould arrow quartertone accidentals (24-EDO)

### PR DESCRIPTION
**Pull request by mdgood**

### CODE REVIEW

**Comment by jsawruk** [comment]
Verified that the entities double-sharp-down, double-sharp-up, flat-flat-down, flat-flat-up, arrow-down, and arrow-up were in the musicxml.xsd, note.mod, and to30.xsl files.

**Comment by school510587** [comment]
double-slash-flat, sharp-1, sharp-2, sharp-3, sharp-5,
        flat-1, flat-2, flat-3, flat-4, sori, koron, and other.
I think sharp-5 is a typo, may be sharp-4.

**Comment by mdgood** [comment]
No, sharp-5 is correct. That's the accidental5CommaSharp glyph in SMuFL. There is no sharp-4 in the Turkish Folk Music accidental system.

**Comment by school510587** [comment]
Thanks, though it seems odd.

**Comment by smoge** [comment]
BTW Bravura/SMuFL has all the symbols necessary for 48ET (quarter-tones + arrows for eighth-tones, the de facto standard in contemporary music practice) and 72ET (Maneri-Sims notation, the choice for those using 72ET). MusicXML should be able to switch between 48ET and 72ET conventions since they are not compatible.

**Comment by mdgood** [comment]
This is handled by issue #109 (pull request #130) which allows you to specify any specific SMuFL glyph for an accidental. The accidental element value can either be one of MusicXML's predefined accidentals, or "other" in case the accidental is not defined in MusicXML 3.1.

**Comment by smoge** [comment]
Arrows are NOT the standard for quarter-tones. Lilypond does it right for
quarter-tones

**Comment by mdgood** [comment]
There are many microtonal and quarter-tone accidental systems. MusicXML 3.0 already supported the glyphs listed in SMuFL's Stein-Zimmerman accidental range, which I believe is what LilyPond uses. This issue involved adding the Gould arrow quartertone accidental range to that, not replacing it. Issue #109 then provides a way to use any SMuFL accidental glyph as needed.

Other SMuFL microtonal ranges already supported by MusicXML 3.0 are the Arel-Ezgi-Uzdilek (AEU) accidentals, Turkish folk music accidentals, and Persian accidentals.

**Pull request merged**
